### ISSUE TITLE
Question about licence

### ISSUE THREAD

**Issue by MihailTrajkovski** [ApexGameTools/Apex-Game-Tools#1]
Hello,

So I am interested in what Apex Utility AI offers but I've got an licensing issue. Basically LGPL licence is a total mystery to me, mainly because as I've read about it it mentions wrappers dinamically linked stuff etc which I don't really understand honestly. So basically:
What would I need to put in the final release of my game?
What would I need to do in order to not release the source of my game(if I download it from the asset store)?

Thank you for your answer in advance.

**Comment by Geminior** [comment]
Hi,

The only thing you are not allowed to do is to package and resell Apex AI
or directly derivative work.
If you make changes to Apex AI you must make those changes available for
others to use as well, e.g. by creating a fork or contributing to someone
else's fork.

There are no restrictions on using Apex AI in a game. You are not required
to publish your game's source code.
The whole reason we made it open source was to allow game devs to use it
and at the same time enable them to share any improvements they might make
to the original.

I hope that answers your question.

Best Regards
Thomas Scheelhardt

**Comment by MihailTrajkovski** [comment]
That's great, thank you for your quick answer. Licenses are always tricky(for me at least) so better to ask than to be sorry.
